[general]
input = apls/arms.simc
output = out/arms.txt

[replacements]
battlelord.up=0
battlelord.remains=0
talent.bloodletting=1
talent.cleave=1
talent.crushing_force=0
talent.deep_wounds=1
talent.demolish=1
talent.massacre.enabled=1
talent.rend=1
talent.slayers_dominance=1
talent.tactical_edge=1