[general]
input = simc/ActionPriorityLists/default/demonhunter_devourer.simc
output = out/devourer.txt
 
[replacements]
talent.collapsing_star=1
talent.devourers_bite=1
talent.duty_eternal=0
talent.eradicate=1
talent.hungering_slash=0
talent.scythes_embrace=1
talent.star_fragments=1
talent.the_hunt=0
talent.voidfall=1
talent.voidsurge=0