[general]
input = simc/ActionPriorityLists/default/rogue_outlaw.simc
output = out/outlaw.txt

[replacements]
hero_tree.fatebound=0
set_bonus.mid1_2pc=1
talent.audacity=0
talent.deal_fate=0
talent.deft_maneuvers=1
talent.fan_the_hammer.rank=2
talent.fan_the_hammer=1
talent.hidden_opportunity=0
talent.improved_adrenaline_rush=1
talent.improved_ambush=0
talent.quick_draw=1
talent.supercharger=1
talent.zero_in=1