[general]
input = simc/ActionPriorityLists/default/rogue_outlaw.simc
output = out/outlaw_OLD.txt

[replacements]
greenskins_wickers.up = 0
set_bonus.tww2_4pc = 0
set_bonus.tww3_trickster_4pc = 0
shadowmeld.up = 0
talent.audacity.enabled = 0
talent.audacity = 0
talent.crackshot = 1
talent.deft_maneuvers = 1
talent.edge_case = 0
talent.fan_the_hammer.rank = 1
talent.fan_the_hammer = 1
talent.flawless_form = 0
talent.greenskins_wickers = 0
talent.hand_of_fate = 0
talent.hidden_opportunity = 0
talent.improved_adrenaline_rush = 1
talent.improved_ambush = 0
talent.keep_it_rolling = 0
talent.killing_spree = 1
talent.loaded_dice = 1
talent.mean_streak = 0
talent.quick_draw.enabled = 1
talent.quick_draw = 1
talent.ruthlessness = 1
talent.subterfuge = 1
talent.supercharger = 1
talent.underhanded_upper_hand = 1
talent.unseen_blade = 1
talent.take_em_by_surprise = 0
talent.double_jeopardy = 0
stealthed.all = stealthed