[general]
input = simc/ActionPriorityLists/default/rogue_assassination.simc
output = out/sin_dungeon_aoe.txt

[replacements]
talent.amplifying_poison = 0
talent.arterial_precision = 1
talent.blindside = 1
talent.caustic_spatter = 1
talent.crimson_tempest.enabled = 1
talent.dashing_scoundrel = 0
talent.deathstalkers_mark = 1
talent.hand_of_fate = 0
talent.improved_garrote = 1
talent.indiscriminate_carnage = 1
talent.inevitabile_end = 0
talent.kingsbane = 0
talent.lightweight_shiv.enabled = 1
talent.lightweight_shiv = 1
talent.master_assassin.enabled = 1
talent.master_assassin = 1
talent.momentum_of_despair = 0
talent.poison_bomb = 0
talent.scent_of_blood.rank = 2
talent.shrouded_suffocation = 1
talent.subterfuge.rank = 0
talent.subterfuge = 2
talent.thrown_precision = 1
talent.vicious_venoms.rank = 2
talent.vicious_venoms = 0
talent.zoldyck_recipe = 1
single_target = 0