[general]
input = simc/ActionPriorityLists/default/rogue_assassination.simc
output = out/sin_raid_cleave.txt

[replacements]
darkest_night.up = 0
talent.blindside = 1
talent.crimson_tempest = 1
talent.improved_garrote = 0
talent.razor_wire = 0
talent.toxic_stiletto = 1