[general]
input = simc/ActionPriorityLists/default/rogue_assassination.simc
output = out/sin_raid_fok.txt

[replacements]
darkest_night.up = 0
talent.blindside = 0
talent.crimson_tempest = 0
talent.improved_garrote = 1
talent.razor_wire = 1
talent.toxic_stiletto = 1
single_target = 0