[general]
input = simc/ActionPriorityLists/default/rogue_subtlety.simc
output = out/sub_raid.txt

[replacements]
darkest_night.up=0
talent.death_perception=1
talent.deathstalkers_mark=0
talent.flagellation=1
talent.premeditation=1
talent.replicating_shadows=1
talent.shadow_blades=1
talent.the_first_dance=0
talent.the_rotten=0
talent.unseen_blade=1
