[general]
input = simc/ActionPriorityLists/default/rogue_subtlety.simc
output = out/sub_raid.txt

[replacements]
talent.ancient_arts_3=1
talent.danse_macabre=0
talent.deathstalkers_mark=1
talent.unseen_blade=0