[general]
input = simc/ActionPriorityLists/default/deathknight_unholy.simc
output = out/unholy_rider.txt
 
[replacements]
talent.army_of_the_dead=1
talent.blightburst=1
talent.commander_of_the_dead=1
talent.dark_transformation=1
talent.desecrate=0
talent.festering_scythe=1
talent.gift_of_the_sanlayn=0
talent.infliction_of_sorrow=0
talent.pestilence=0
talent.reaping=1
talent.soul_reaper=1
talent.summon_gargoyle=0