[general]
input = simc/ActionPriorityLists/mage_arcane.simc
output = out/arcane_dungeon.txt

[replacements]
talent.arcing_cleave = 1
talent.evocation = 1
talent.arcane_bombardment = 1
talent.spellfire_spheres = 0
talent.high_voltage = 1
talent.charged_orb = 1
talent.unerring_proficiency = 0
talent.orb_barrage = 1
talent.magis_spark = 1
talent.time_loop = 0
talent.reverberate = 0
talent.resonance = 1
talent.consortiums_bauble = 0
talent.leydrinker = 0
talent.shifting_shards = 0